### ISSUE TITLE
SchemaMismatch: Error during transform of User

### ISSUE THREAD

**Issue by briansloane** [singer-io/tap-pipedrive#13]
last_login: 0000-00-00 00:00:00 does not match {'type': ['string', 'null'], 'format': 'date-time'}

```
2018-02-08 21:37:18,378Z    tap - Traceback (most recent call last):
2018-02-08 21:37:18,378Z    tap -   File "tap-env/bin/tap-pipedrive", line 11, in <module>
2018-02-08 21:37:18,381Z    tap -     sys.exit(main())
2018-02-08 21:37:18,381Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 30, in main
2018-02-08 21:37:18,381Z    tap -     raise e
2018-02-08 21:37:18,381Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 27, in main
2018-02-08 21:37:18,381Z    tap -     main_impl()
2018-02-08 21:37:18,381Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 22, in main_impl
2018-02-08 21:37:18,382Z    tap -     pipedrive_tap.do_sync()
2018-02-08 21:37:18,382Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/tap.py", line 94, in do_sync
2018-02-08 21:37:18,382Z    tap -     row = optimus_prime.transform(row, stream.get_schema())
2018-02-08 21:37:18,382Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/transform.py", line 94, in transform
2018-02-08 21:37:18,382Z    tap -     raise SchemaMismatch(self.errors)
2018-02-08 21:37:18,382Z    tap - singer.transform.SchemaMismatch: Errors during transform
2018-02-08 21:37:18,382Z    tap - 	last_login: 0000-00-00 00:00:00 does not match {'type': ['string', 'null'], 'format': 'date-time'}
```

**Comment by briansloane** [comment]
Duplicate of https://github.com/singer-io/tap-pipedrive/issues/14
