### ISSUE TITLE
Pipedrive extraction of deaflow error

### ISSUE THREAD

**Issue by leimonio** [singer-io/tap-pipedrive#59]
Hi there, thank you very much for contributing and maintaing this opensource project for extracting pipedrive information! 🙌🏻

I've been using [Stitch](https://www.stitchdata.com/) lately and for syncing my pipedrive accounts to a database. For some of these accounts, the extraction of `dealflows` is failing with an error
```
argument of type 'NoneType' is not iterable
```

Trying to understand what is the issue that makes extraction fail. Is this something that could possibly be fixed?

In case this is more helpful, here you can see a full log and the respective errored stack trace:
```
2019-07-09 05:00:31,687Z   main - INFO Running tap-pipedrive version 1.0.4 and target-stitch version 1.8.1
2019-07-09 05:00:31,768Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-pipedrive --config /tmp/tap_discover_config.json --discover
2019-07-09 05:00:31,940Z    tap - INFO Starting discover
2019-07-09 05:00:33,849Z    tap - INFO Finished discover
2019-07-09 05:00:33,876Z   main - INFO Tap exited normally.
2019-07-09 05:00:33,879Z   main - INFO Saving list of discovered streams
2019-07-09 05:00:33,935Z   main - INFO Saving structure of stream currency
2019-07-09 05:00:33,985Z   main - INFO Saving structure of stream activity_types
2019-07-09 05:00:34,007Z   main - INFO Saving structure of stream stages
2019-07-09 05:00:34,065Z   main - INFO Saving structure of stream filters
2019-07-09 05:00:34,087Z   main - INFO Saving structure of stream pipelines
2019-07-09 05:00:34,105Z   main - INFO Saving structure of stream notes
2019-07-09 05:00:34,129Z   main - INFO Saving structure of stream users
2019-07-09 05:00:34,147Z   main - INFO Saving structure of stream activities
2019-07-09 05:00:34,213Z   main - INFO Saving structure of stream deals
2019-07-09 05:00:34,322Z   main - INFO Saving structure of stream files
2019-07-09 05:00:34,528Z   main - INFO Saving structure of stream organizations
2019-07-09 05:00:34,604Z   main - INFO Saving structure of stream persons
2019-07-09 05:00:34,686Z   main - INFO Saving structure of stream products
2019-07-09 05:00:34,767Z   main - INFO Saving structure of stream delete_log
2019-07-09 05:00:34,782Z   main - INFO Saving structure of stream dealflow
2019-07-09 05:00:34,826Z   main - INFO Saving structure of stream deal_products
2019-07-09 05:00:34,904Z   main - INFO Getting list of selected properties
2019-07-09 05:00:35,183Z   main - INFO Starting tap: tap-env/bin/tap-pipedrive --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
2019-07-09 05:00:35,188Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2019-07-09 05:00:35,363Z    tap - INFO Skipping stream activities as resuming from dealflow
2019-07-09 05:00:35,363Z    tap - INFO Skipping stream deals as resuming from dealflow
2019-07-09 05:00:35,364Z    tap - INFO Skipping stream persons as resuming from dealflow
2019-07-09 05:00:35,364Z    tap - INFO Resuming from dealflow
2019-07-09 05:00:35,455Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch
2019-07-09 05:00:35,456Z   main - INFO State update: adding bookmarks.activities.update_time = "2019-07-05T23:58:03+00:00"
2019-07-09 05:00:35,456Z   main - INFO State update: adding bookmarks.dealflow.log_time = "2018-01-01T00:00:00+00:00"
2019-07-09 05:00:35,456Z   main - INFO State update: adding bookmarks.deals.update_time = "2019-07-06T05:08:31+00:00"
2019-07-09 05:00:35,456Z   main - INFO State update: adding bookmarks.persons.update_time = "2019-07-06T05:08:31+00:00"
2019-07-09 05:00:35,456Z   main - INFO State update: adding currently_syncing = "dealflow"
2019-07-09 05:00:35,895Z    tap - INFO HTTP request to "dealflow" endpoint took 0.530s, returned status code 200
2019-07-09 05:00:36,962Z    tap - INFO HTTP request to "dealflow" endpoint took 1.046s, returned status code 200
2019-07-09 05:00:36,966Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:36,966Z    tap - 	change_source_user_agent
2019-07-09 05:00:36,966Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:36,966Z    tap - INFO replicated 1 records from "dealflow" endpoint
2019-07-09 05:00:37,467Z    tap - INFO HTTP request to "dealflow" endpoint took 0.500s, returned status code 200
2019-07-09 05:00:37,960Z    tap - INFO HTTP request to "dealflow" endpoint took 0.472s, returned status code 200
2019-07-09 05:00:38,452Z    tap - INFO HTTP request to "dealflow" endpoint took 0.470s, returned status code 200
2019-07-09 05:00:39,621Z    tap - INFO HTTP request to "dealflow" endpoint took 1.148s, returned status code 200
2019-07-09 05:00:39,630Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:39,630Z    tap - 	change_source_user_agent
2019-07-09 05:00:39,630Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:39,630Z    tap - INFO replicated 3 records from "dealflow" endpoint
2019-07-09 05:00:40,098Z    tap - INFO HTTP request to "dealflow" endpoint took 0.468s, returned status code 200
2019-07-09 05:00:40,940Z    tap - INFO HTTP request to "dealflow" endpoint took 0.821s, returned status code 200
2019-07-09 05:00:40,947Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:40,947Z    tap - 	change_source_user_agent
2019-07-09 05:00:40,947Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:40,947Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:00:41,314Z    tap - INFO HTTP request to "dealflow" endpoint took 0.366s, returned status code 200
2019-07-09 05:00:41,811Z    tap - INFO HTTP request to "dealflow" endpoint took 0.477s, returned status code 200
2019-07-09 05:00:42,450Z    tap - INFO HTTP request to "dealflow" endpoint took 0.620s, returned status code 200
2019-07-09 05:00:42,452Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:42,452Z    tap - 	change_source_user_agent
2019-07-09 05:00:42,452Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:42,452Z    tap - INFO replicated 1 records from "dealflow" endpoint
2019-07-09 05:00:42,910Z    tap - INFO HTTP request to "dealflow" endpoint took 0.457s, returned status code 200
2019-07-09 05:00:43,397Z    tap - INFO HTTP request to "dealflow" endpoint took 0.466s, returned status code 200
2019-07-09 05:00:43,918Z    tap - INFO HTTP request to "dealflow" endpoint took 0.502s, returned status code 200
2019-07-09 05:00:44,416Z    tap - INFO HTTP request to "dealflow" endpoint took 0.475s, returned status code 200
2019-07-09 05:00:44,833Z    tap - INFO HTTP request to "dealflow" endpoint took 0.379s, returned status code 200
2019-07-09 05:00:44,837Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:44,837Z    tap - 	change_source_user_agent
2019-07-09 05:00:44,837Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:44,837Z    tap - INFO replicated 1 records from "dealflow" endpoint
2019-07-09 05:00:45,337Z    tap - INFO HTTP request to "dealflow" endpoint took 0.498s, returned status code 200
2019-07-09 05:00:45,774Z    tap - INFO HTTP request to "dealflow" endpoint took 0.399s, returned status code 200
2019-07-09 05:00:45,781Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:45,781Z    tap - 	change_source_user_agent
2019-07-09 05:00:45,782Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:45,782Z    tap - INFO replicated 5 records from "dealflow" endpoint
2019-07-09 05:00:46,385Z    tap - INFO HTTP request to "dealflow" endpoint took 0.601s, returned status code 200
2019-07-09 05:00:46,389Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:46,390Z    tap - 	change_source_user_agent
2019-07-09 05:00:46,390Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:46,390Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:00:46,781Z    tap - INFO HTTP request to "dealflow" endpoint took 0.391s, returned status code 200
2019-07-09 05:00:47,270Z    tap - INFO HTTP request to "dealflow" endpoint took 0.468s, returned status code 200
2019-07-09 05:00:47,755Z    tap - INFO HTTP request to "dealflow" endpoint took 0.466s, returned status code 200
2019-07-09 05:00:48,422Z    tap - INFO HTTP request to "dealflow" endpoint took 0.641s, returned status code 200
2019-07-09 05:00:48,428Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:48,428Z    tap - 	change_source_user_agent
2019-07-09 05:00:48,428Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:48,428Z    tap - INFO replicated 6 records from "dealflow" endpoint
2019-07-09 05:00:49,278Z    tap - INFO HTTP request to "dealflow" endpoint took 0.849s, returned status code 200
2019-07-09 05:00:49,285Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:49,285Z    tap - 	change_source_user_agent
2019-07-09 05:00:49,285Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:49,285Z    tap - INFO replicated 5 records from "dealflow" endpoint
2019-07-09 05:00:49,831Z    tap - INFO HTTP request to "dealflow" endpoint took 0.545s, returned status code 200
2019-07-09 05:00:50,191Z    tap - INFO HTTP request to "dealflow" endpoint took 0.341s, returned status code 200
2019-07-09 05:00:50,196Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:50,196Z    tap - 	change_source_user_agent
2019-07-09 05:00:50,196Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:50,196Z    tap - INFO replicated 7 records from "dealflow" endpoint
2019-07-09 05:00:50,685Z    tap - INFO HTTP request to "dealflow" endpoint took 0.488s, returned status code 200
2019-07-09 05:00:51,186Z    tap - INFO HTTP request to "dealflow" endpoint took 0.480s, returned status code 200
2019-07-09 05:00:51,717Z    tap - INFO HTTP request to "dealflow" endpoint took 0.511s, returned status code 200
2019-07-09 05:00:53,572Z    tap - INFO HTTP request to "dealflow" endpoint took 1.836s, returned status code 200
2019-07-09 05:00:53,579Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:53,579Z    tap - 	change_source_user_agent
2019-07-09 05:00:53,579Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:53,579Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:00:54,067Z    tap - INFO HTTP request to "dealflow" endpoint took 0.488s, returned status code 200
2019-07-09 05:00:54,575Z    tap - INFO HTTP request to "dealflow" endpoint took 0.488s, returned status code 200
2019-07-09 05:00:55,241Z    tap - INFO HTTP request to "dealflow" endpoint took 0.644s, returned status code 200
2019-07-09 05:00:55,250Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:55,251Z    tap - 	change_source_user_agent
2019-07-09 05:00:55,251Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:55,251Z    tap - INFO replicated 8 records from "dealflow" endpoint
2019-07-09 05:00:55,815Z    tap - INFO HTTP request to "dealflow" endpoint took 0.563s, returned status code 200
2019-07-09 05:00:55,820Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:55,821Z    tap - 	change_source_user_agent
2019-07-09 05:00:55,821Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:55,821Z    tap - INFO replicated 4 records from "dealflow" endpoint
2019-07-09 05:00:56,304Z    tap - INFO HTTP request to "dealflow" endpoint took 0.482s, returned status code 200
2019-07-09 05:00:56,953Z    tap - INFO HTTP request to "dealflow" endpoint took 0.629s, returned status code 200
2019-07-09 05:00:57,363Z    tap - INFO HTTP request to "dealflow" endpoint took 0.390s, returned status code 200
2019-07-09 05:00:57,977Z    tap - INFO HTTP request to "dealflow" endpoint took 0.592s, returned status code 200
2019-07-09 05:00:58,563Z    tap - INFO HTTP request to "dealflow" endpoint took 0.565s, returned status code 200
2019-07-09 05:00:58,568Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:58,568Z    tap - 	change_source_user_agent
2019-07-09 05:00:58,568Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:58,568Z    tap - INFO replicated 7 records from "dealflow" endpoint
2019-07-09 05:00:59,603Z    tap - INFO HTTP request to "dealflow" endpoint took 1.034s, returned status code 200
2019-07-09 05:00:59,613Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:00:59,613Z    tap - 	change_source_user_agent
2019-07-09 05:00:59,613Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:00:59,613Z    tap - INFO replicated 5 records from "dealflow" endpoint
2019-07-09 05:01:00,108Z    tap - INFO HTTP request to "dealflow" endpoint took 0.494s, returned status code 200
2019-07-09 05:01:00,762Z    tap - INFO HTTP request to "dealflow" endpoint took 0.633s, returned status code 200
2019-07-09 05:01:00,765Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:00,765Z    tap - 	change_source_user_agent
2019-07-09 05:01:00,765Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:00,765Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:01:01,278Z    tap - INFO HTTP request to "dealflow" endpoint took 0.512s, returned status code 200
2019-07-09 05:01:01,893Z    tap - INFO HTTP request to "dealflow" endpoint took 0.594s, returned status code 200
2019-07-09 05:01:01,897Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:01,897Z    tap - 	change_source_user_agent
2019-07-09 05:01:01,898Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:01,898Z    tap - INFO replicated 3 records from "dealflow" endpoint
2019-07-09 05:01:02,734Z    tap - INFO HTTP request to "dealflow" endpoint took 0.835s, returned status code 200
2019-07-09 05:01:02,743Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:02,743Z    tap - 	change_source_user_agent
2019-07-09 05:01:02,743Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:02,743Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:01:03,122Z    tap - INFO HTTP request to "dealflow" endpoint took 0.378s, returned status code 200
2019-07-09 05:01:03,126Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:03,126Z    tap - 	change_source_user_agent
2019-07-09 05:01:03,126Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:03,126Z    tap - INFO replicated 4 records from "dealflow" endpoint
2019-07-09 05:01:03,652Z    tap - INFO HTTP request to "dealflow" endpoint took 0.525s, returned status code 200
2019-07-09 05:01:04,474Z    tap - INFO HTTP request to "dealflow" endpoint took 0.781s, returned status code 200
2019-07-09 05:01:04,485Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:04,485Z    tap - 	change_source_user_agent
2019-07-09 05:01:04,485Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:04,485Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:01:05,245Z    tap - INFO HTTP request to "dealflow" endpoint took 0.760s, returned status code 200
2019-07-09 05:01:05,252Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:05,252Z    tap - 	change_source_user_agent
2019-07-09 05:01:05,252Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:05,252Z    tap - INFO replicated 5 records from "dealflow" endpoint
2019-07-09 05:01:05,719Z    tap - INFO HTTP request to "dealflow" endpoint took 0.466s, returned status code 200
2019-07-09 05:01:05,721Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:05,721Z    tap - 	change_source_user_agent
2019-07-09 05:01:05,721Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:05,722Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:01:06,230Z    tap - INFO HTTP request to "dealflow" endpoint took 0.508s, returned status code 200
2019-07-09 05:01:06,761Z    tap - INFO HTTP request to "dealflow" endpoint took 0.507s, returned status code 200
2019-07-09 05:01:07,149Z    tap - INFO HTTP request to "dealflow" endpoint took 0.365s, returned status code 200
2019-07-09 05:01:07,153Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:07,154Z    tap - 	change_source_user_agent
2019-07-09 05:01:07,154Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:07,154Z    tap - INFO replicated 3 records from "dealflow" endpoint
2019-07-09 05:01:08,114Z    tap - INFO HTTP request to "dealflow" endpoint took 0.960s, returned status code 200
2019-07-09 05:01:08,124Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:08,124Z    tap - 	change_source_user_agent
2019-07-09 05:01:08,125Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:08,125Z    tap - INFO replicated 4 records from "dealflow" endpoint
2019-07-09 05:01:08,736Z    tap - INFO HTTP request to "dealflow" endpoint took 0.610s, returned status code 200
2019-07-09 05:01:08,742Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:08,743Z    tap - 	change_source_user_agent
2019-07-09 05:01:08,743Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:08,743Z    tap - INFO replicated 4 records from "dealflow" endpoint
2019-07-09 05:01:09,246Z    tap - INFO HTTP request to "dealflow" endpoint took 0.502s, returned status code 200
2019-07-09 05:01:09,252Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:09,252Z    tap - 	change_source_user_agent
2019-07-09 05:01:09,252Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:09,252Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:01:09,788Z    tap - INFO HTTP request to "dealflow" endpoint took 0.534s, returned status code 200
2019-07-09 05:01:10,250Z    tap - INFO HTTP request to "dealflow" endpoint took 0.441s, returned status code 200
2019-07-09 05:01:10,256Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:10,256Z    tap - 	change_source_user_agent
2019-07-09 05:01:10,256Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:10,256Z    tap - INFO replicated 7 records from "dealflow" endpoint
2019-07-09 05:01:11,241Z    tap - INFO HTTP request to "dealflow" endpoint took 0.985s, returned status code 200
2019-07-09 05:01:11,251Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:11,251Z    tap - 	change_source_user_agent
2019-07-09 05:01:11,251Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:11,251Z    tap - INFO replicated 1 records from "dealflow" endpoint
2019-07-09 05:01:11,950Z    tap - INFO HTTP request to "dealflow" endpoint took 0.698s, returned status code 200
2019-07-09 05:01:12,906Z    tap - INFO HTTP request to "dealflow" endpoint took 0.932s, returned status code 200
2019-07-09 05:01:12,917Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:12,917Z    tap - 	change_source_user_agent
2019-07-09 05:01:12,917Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:12,918Z    tap - INFO replicated 1 records from "dealflow" endpoint
2019-07-09 05:01:13,231Z    tap - INFO HTTP request to "dealflow" endpoint took 0.312s, returned status code 200
2019-07-09 05:01:13,232Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:13,232Z    tap - 	change_source_user_agent
2019-07-09 05:01:13,232Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:13,232Z    tap - INFO replicated 0 records from "dealflow" endpoint
2019-07-09 05:01:13,754Z    tap - INFO HTTP request to "dealflow" endpoint took 0.522s, returned status code 200
2019-07-09 05:01:14,730Z    tap - INFO HTTP request to "dealflow" endpoint took 0.953s, returned status code 200
2019-07-09 05:01:14,741Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:14,741Z    tap - 	change_source_user_agent
2019-07-09 05:01:14,741Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:14,741Z    tap - INFO replicated 10 records from "dealflow" endpoint
2019-07-09 05:01:15,602Z    tap - INFO HTTP request to "dealflow" endpoint took 0.861s, returned status code 200
2019-07-09 05:01:15,611Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:15,611Z    tap - 	change_source_user_agent
2019-07-09 05:01:15,611Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:15,612Z    tap - INFO replicated 4 records from "dealflow" endpoint
2019-07-09 05:01:16,209Z    tap - INFO HTTP request to "dealflow" endpoint took 0.596s, returned status code 200
2019-07-09 05:01:16,817Z    tap - INFO HTTP request to "dealflow" endpoint took 0.587s, returned status code 200
2019-07-09 05:01:17,725Z    tap - INFO HTTP request to "dealflow" endpoint took 0.888s, returned status code 200
2019-07-09 05:01:17,734Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:17,734Z    tap - 	change_source_user_agent
2019-07-09 05:01:17,734Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:17,735Z    tap - INFO replicated 5 records from "dealflow" endpoint
2019-07-09 05:01:18,246Z    tap - INFO HTTP request to "dealflow" endpoint took 0.511s, returned status code 200
2019-07-09 05:01:18,846Z    tap - INFO HTTP request to "dealflow" endpoint took 0.573s, returned status code 200
2019-07-09 05:01:18,852Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:18,852Z    tap - 	change_source_user_agent
2019-07-09 05:01:18,852Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:18,853Z    tap - INFO replicated 1 records from "dealflow" endpoint
2019-07-09 05:01:19,458Z    tap - INFO HTTP request to "dealflow" endpoint took 0.605s, returned status code 200
2019-07-09 05:01:20,375Z    tap - INFO HTTP request to "dealflow" endpoint took 0.894s, returned status code 200
2019-07-09 05:01:20,384Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:20,384Z    tap - 	change_source_user_agent
2019-07-09 05:01:20,384Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:20,384Z    tap - INFO replicated 2 records from "dealflow" endpoint
2019-07-09 05:01:21,063Z    tap - INFO HTTP request to "dealflow" endpoint took 0.678s, returned status code 200
2019-07-09 05:01:21,072Z    tap - WARNING Removed 1 paths during transforms:
2019-07-09 05:01:21,072Z    tap - 	change_source_user_agent
2019-07-09 05:01:21,072Z    tap - WARNING Removed paths list: ['change_source_user_agent']
2019-07-09 05:01:21,073Z    tap - INFO replicated 5 records from "dealflow" endpoint
2019-07-09 05:01:21,632Z    tap - INFO HTTP request to "dealflow" endpoint took 0.559s, returned status code 200
2019-07-09 05:01:21,650Z    tap - CRITICAL argument of type 'NoneType' is not iterable
2019-07-09 05:01:21,654Z    tap - Traceback (most recent call last):
2019-07-09 05:01:21,654Z    tap -   File "tap-env/bin/tap-pipedrive", line 10, in <module>
2019-07-09 05:01:21,654Z    tap -     sys.exit(main())
2019-07-09 05:01:21,654Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 34, in main
2019-07-09 05:01:21,654Z    tap -     raise e
2019-07-09 05:01:21,654Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 31, in main
2019-07-09 05:01:21,654Z    tap -     main_impl()
2019-07-09 05:01:21,655Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 26, in main_impl
2019-07-09 05:01:21,655Z    tap -     pipedrive_tap.do_sync(catalog)
2019-07-09 05:01:21,655Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/tap.py", line 124, in do_sync
2019-07-09 05:01:21,655Z    tap -     for deal_id in stream.get_deal_ids(self):
2019-07-09 05:01:21,655Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/stream.py", line 164, in get_deal_ids
2019-07-09 05:01:21,655Z    tap -     this_page_ids = self.find_deal_ids(response.json()['data'], start=checkpoint, stop=self.stream_start)
2019-07-09 05:01:21,655Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/stream.py", line 174, in find_deal_ids
2019-07-09 05:01:21,655Z    tap -     added_ids = [data[i]['id'] for i in range(len(data)) if (start <= pendulum.parse(data[i]['add_time']) < stop)]
2019-07-09 05:01:21,655Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/stream.py", line 174, in <listcomp>
2019-07-09 05:01:21,655Z    tap -     added_ids = [data[i]['id'] for i in range(len(data)) if (start <= pendulum.parse(data[i]['add_time']) < stop)]
2019-07-09 05:01:21,655Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pendulum/parser.py", line 20, in parse
2019-07-09 05:01:21,656Z    tap -     return _parse(text, **options)
2019-07-09 05:01:21,656Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pendulum/parser.py", line 36, in _parse
2019-07-09 05:01:21,656Z    tap -     parsed = base_parse(text, **options)
2019-07-09 05:01:21,656Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pendulum/parsing/__init__.py", line 70, in parse
2019-07-09 05:01:21,656Z    tap -     return _normalize(_parse(text, **_options), **_options)
2019-07-09 05:01:21,656Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pendulum/parsing/__init__.py", line 111, in _parse
2019-07-09 05:01:21,656Z    tap -     return _parse_iso8601_interval(text)
2019-07-09 05:01:21,656Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/pendulum/parsing/__init__.py", line 211, in _parse_iso8601_interval
2019-07-09 05:01:21,656Z    tap -     if "/" not in text:
2019-07-09 05:01:21,656Z    tap - TypeError: argument of type 'NoneType' is not iterable
2019-07-09 05:01:21,679Z target - INFO Sending batch with 128 messages for table dealflow to https://api.stitchdata.com/v2/import/batch
2019-07-09 05:01:21,826Z target - INFO Exiting normally
2019-07-09 05:01:21,871Z   main - INFO Target exited normally with status 0
2019-07-09 05:01:21,872Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "argument of type 'NoneType' is not iterable". Target succeeded.
```

**Comment by luandy64** [comment]
Looks like an error on this line, https://github.com/singer-io/tap-pipedrive/blob/4b1a20697132ec03b1ef829728ea8dc00ae4cdca/tap_pipedrive/stream.py#L174

Does this error happen with all streams? Or do you know which ones are affected?

**Comment by denield** [comment]
That's indeed where the error was @luandy64, opened a PR (#67) to fix. The issue is that `add_time` could be `None` which is not handled here. Added an example to reproduce it into the PR.

**Comment by alb150** [comment]
experiencing this same issue in my extration since yesterday. Is it still being worked on?
