### ISSUE TITLE
PD extraction error 401 

### ISSUE THREAD

**Issue by smbeard14** [singer-io/tap-pipedrive#66]
Hello I have an urgent issue of our PD extraction not running. I am getting an error 401 since 17/10. It had worked for a very long time before this. I would appreciate any help ASAP. 

2019-10-18 07:32:28,694Z   main - INFO Running tap-pipedrive version 0.2.5 and target-stitch version 1.8.1
2019-10-18 07:32:28,767Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-pipedrive --config /tmp/tap_discover_config.json --discover
2019-10-18 07:32:28,974Z    tap - INFO Starting discover
2019-10-18 07:32:29,040Z    tap - CRITICAL Invalid response from API, status code is 401
2019-10-18 07:32:29,046Z    tap - Traceback (most recent call last):
2019-10-18 07:32:29,046Z    tap -   File "tap-env/bin/tap-pipedrive", line 10, in <module>
2019-10-18 07:32:29,047Z    tap -     sys.exit(main())
2019-10-18 07:32:29,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 34, in main
2019-10-18 07:32:29,051Z    tap -     raise e
2019-10-18 07:32:29,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 31, in main
2019-10-18 07:32:29,051Z    tap -     main_impl()
2019-10-18 07:32:29,051Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/cli.py", line 18, in main_impl
2019-10-18 07:32:29,052Z    tap -     catalog = pipedrive_tap.do_discover()
2019-10-18 07:32:29,052Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/tap.py", line 73, in do_discover
2019-10-18 07:32:29,052Z    tap -     schema = Schema.from_dict(stream.get_schema())
2019-10-18 07:32:29,052Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/streams/recents/dynamic_typing/__init__.py", line 64, in get_schema
2019-10-18 07:32:29,052Z    tap -     raise e
2019-10-18 07:32:29,052Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_pipedrive/streams/recents/dynamic_typing/__init__.py", line 25, in get_schema
2019-10-18 07:32:29,052Z    tap -     'status code is {}'.format(fields_response.status_code)
2019-10-18 07:32:29,053Z    tap - AssertionError: Invalid response from API, status code is 401
2019-10-18 07:32:29,087Z   main - INFO Tap exited abnormally with status 1
2019-10-18 07:32:29,089Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "Invalid response from API, status code is 401".

**Comment by henriquerossato** [comment]
Hello, is there any update regarding it ?

**Comment by seckindinc** [comment]
Same issue today.
