### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe When I use `tap-pipedrive` with `target-postgres`

### ISSUE THREAD

**Issue by stephane-klein** [singer-io/tap-pipedrive#76]
When I use `tap-pipedrive` with `target-postgres` I have this error

```
$  tap-pipedrive --config pipedrive-tap-config.json | ./.venv/bin/target-postgres --config target_postgres_config.json
INFO PostgresTarget created with established connection: `user=postgres password=xxx dbname=postgres host=127.0.0.1 port=5432`, PostgreSQL schema: `pipedrive`
INFO Sending version information to singer.io. To disable sending anonymous usage data, set the config parameter "disable_collection" to true
INFO Starting discover
ERROR Unable to parse JSON: sync

CRITICAL Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./.venv/bin/target-postgres", line 10, in <module>
    sys.exit(cli())
  File "/Users/stephane/Work/stephane-klein/.venv/lib/python3.7/site-packages/target_postgres/__init__.py", line 45, in cli
    main(args.config)
  File "/Users/stephane/Work/stephane-klein/.venv/lib/python3.7/site-packages/target_postgres/__init__.py", line 39, in main
    target_tools.main(postgres_target)
  File "/Users/stephane/Work/stephane-klein/.venv/lib/python3.7/site-packages/target_postgres/target_tools.py", line 28, in main
    stream_to_target(input_stream, target, config=config)
  File "/Users/stephane/Work/stephane-klein/.venv/lib/python3.7/site-packages/target_postgres/target_tools.py", line 77, in stream_to_target
    raise e
  File "/Users/stephane/Work/stephane-klein/.venv/lib/python3.7/site-packages/target_postgres/target_tools.py", line 64, in stream_to_target
    line
  File "/Users/stephane/Work/stephane-klein/.venv/lib/python3.7/site-packages/target_postgres/target_tools.py", line 94, in _line_handler
    line_data = json.loads(line, parse_float=decimal.Decimal)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.2077040672302246, "tags": {"endpoint": "currency", "http_status_code": 200, "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 0, "tags": {"endpoint": "currency"}}
CRITICAL [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Users/stephane/Work/stephane-klein/.venv2/bin/tap-pipedrive", line 11, in <module>
    load_entry_point('tap-pipedrive', 'console_scripts', 'tap-pipedrive')()
  File "/Users/stephane/Work/stephane-klein/src/tap-pipedrive/tap_pipedrive/cli.py", line 35, in main
    raise e
  File "/Users/stephane/Work/stephane-klein/src/tap-pipedrive/tap_pipedrive/cli.py", line 32, in main
    main_impl()
  File "/Users/stephane/Work/stephane-klein/src/tap-pipedrive/tap_pipedrive/cli.py", line 27, in main_impl
    pipedrive_tap.do_sync(catalog)
  File "/Users/stephane/Work/stephane-klein/src/tap-pipedrive/tap_pipedrive/tap.py", line 154, in do_sync
    self.do_paginate(stream, stream_metadata)
  File "/Users/stephane/Work/stephane-klein/src/tap-pipedrive/tap_pipedrive/tap.py", line 203, in do_paginate
    if stream.write_record(row):
  File "/Users/stephane/Work/stephane-klein/src/tap-pipedrive/tap_pipedrive/stream.py", line 108, in write_record
    singer.write_record(self.schema, row)
  File "/Users/stephane/Work/stephane-klein/.venv2/lib/python3.7/site-packages/singer/messages.py", line 228, in write_record
    time_extracted=time_extracted))
  File "/Users/stephane/Work/stephane-klein/.venv2/lib/python3.7/site-packages/singer/messages.py", line 218, in write_message
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by stephane-klein** [comment]
It works here: https://github.com/stephane-klein/singer-pipedrive-playground
